[package]
name = "r34-board-downloader"
version = "0.6.9"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r34_api = "0.2.6"
tokio = {version = "1.37.0", features = ["full"]}
reqwest = "0.12.4"
indicatif = "0.17.8"